# Generated by Django 5.2.7 on 2025-10-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='payment',
        ),
    ]
