# Generated by Django 5.2.7 on 2025-10-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_invite_payment'),
        ('payments', '0002_payment_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
    ]
